<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="2" ignored="0" total="5" passed="1" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-02-26T15:34:25 IST" name="Suite" finished-at="2025-02-26T15:34:42 IST" duration-ms="16372">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidationsTest.loginIncorrectCredentialsTest()[pri:0, instance:AutomationPractice.ErrorValidationsTest@7dc19a70]" name="loginIncorrectCredentialsTest" class="AutomationPractice.ErrorValidationsTest"/>
      </group> <!-- ErrorHandling -->
      <group name="Regression">
        <method signature="EndToEndTestPOM.endToEndTest(java.util.HashMap)[pri:0, instance:AutomationPractice.EndToEndTestPOM@7bd7d6d6]" name="endToEndTest" class="AutomationPractice.EndToEndTestPOM"/>
      </group> <!-- Regression -->
    </groups>
    <test started-at="2025-02-26T15:34:25 IST" name="LoginPageErrorValidation" finished-at="2025-02-26T15:34:34 IST" duration-ms="8417">
      <class name="AutomationPractice.ErrorValidationsTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:AutomationPractice.ErrorValidationsTest@7dc19a70]" started-at="2025-02-26T15:34:25 IST" name="launchApplication" finished-at="2025-02-26T15:34:28 IST" duration-ms="2840" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="loginIncorrectCredentialsTest()[pri:0, instance:AutomationPractice.ErrorValidationsTest@7dc19a70]" started-at="2025-02-26T15:34:28 IST" name="loginIncorrectCredentialsTest" finished-at="2025-02-26T15:34:30 IST" duration-ms="1495" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect1 email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect1 email or password.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at AutomationPractice.ErrorValidationsTest.loginIncorrectCredentialsTest(ErrorValidationsTest.java:20)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:569)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginIncorrectCredentialsTest -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:AutomationPractice.ErrorValidationsTest@7dc19a70]" started-at="2025-02-26T15:34:30 IST" name="closeBrowser" finished-at="2025-02-26T15:34:30 IST" duration-ms="250" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:AutomationPractice.ErrorValidationsTest@7dc19a70]" started-at="2025-02-26T15:34:30 IST" name="launchApplication" finished-at="2025-02-26T15:34:32 IST" duration-ms="1857" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="loginIncorrectCredentialsTest()[pri:0, instance:AutomationPractice.ErrorValidationsTest@7dc19a70]" started-at="2025-02-26T15:34:32 IST" name="loginIncorrectCredentialsTest" finished-at="2025-02-26T15:34:33 IST" duration-ms="1080" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect1 email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect1 email or password.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at AutomationPractice.ErrorValidationsTest.loginIncorrectCredentialsTest(ErrorValidationsTest.java:20)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:569)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginIncorrectCredentialsTest -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:AutomationPractice.ErrorValidationsTest@7dc19a70]" started-at="2025-02-26T15:34:34 IST" name="closeBrowser" finished-at="2025-02-26T15:34:34 IST" duration-ms="200" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- AutomationPractice.ErrorValidationsTest -->
    </test> <!-- LoginPageErrorValidation -->
    <test started-at="2025-02-26T15:34:25 IST" name="PurchaseOrder" finished-at="2025-02-26T15:34:42 IST" duration-ms="16372">
      <class name="AutomationPractice.EndToEndTestPOM">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:AutomationPractice.EndToEndTestPOM@7bd7d6d6]" started-at="2025-02-26T15:34:26 IST" name="launchApplication" finished-at="2025-02-26T15:34:29 IST" duration-ms="3877" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="endToEndTest(java.util.HashMap)[pri:0, instance:AutomationPractice.EndToEndTestPOM@7bd7d6d6]" started-at="2025-02-26T15:34:29 IST" name="endToEndTest" data-provider="getData" finished-at="2025-02-26T15:34:34 IST" duration-ms="4247" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{country=India, password=Vijay@619., product=ADIDAS ORIGINAL, mail=vijay619@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endToEndTest -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:AutomationPractice.EndToEndTestPOM@7bd7d6d6]" started-at="2025-02-26T15:34:34 IST" name="closeBrowser" finished-at="2025-02-26T15:34:34 IST" duration-ms="227" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:AutomationPractice.EndToEndTestPOM@7bd7d6d6]" started-at="2025-02-26T15:34:34 IST" name="launchApplication" finished-at="2025-02-26T15:34:37 IST" duration-ms="2595" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="ordersPageValidation(java.util.HashMap)[pri:0, instance:AutomationPractice.EndToEndTestPOM@7bd7d6d6]" started-at="2025-02-26T15:34:37 IST" name="ordersPageValidation" data-provider="getData" finished-at="2025-02-26T15:34:38 IST" duration-ms="1548" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[{country=India, password=Vijay@619., product=ADIDAS ORIGINAL, mail=vijay619@gmail.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at AutomationPractice.EndToEndTestPOM.ordersPageValidation(EndToEndTestPOM.java:55)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:569)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ordersPageValidation -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:AutomationPractice.EndToEndTestPOM@7bd7d6d6]" started-at="2025-02-26T15:34:38 IST" name="closeBrowser" finished-at="2025-02-26T15:34:38 IST" duration-ms="200" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:AutomationPractice.EndToEndTestPOM@7bd7d6d6]" started-at="2025-02-26T15:34:38 IST" name="launchApplication" finished-at="2025-02-26T15:34:40 IST" duration-ms="1580" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="ordersPageValidation(java.util.HashMap)[pri:0, instance:AutomationPractice.EndToEndTestPOM@7bd7d6d6]" started-at="2025-02-26T15:34:40 IST" name="ordersPageValidation" data-provider="getData" finished-at="2025-02-26T15:34:41 IST" duration-ms="1482" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{country=India, password=Vijay@619., product=ADIDAS ORIGINAL, mail=vijay619@gmail.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at AutomationPractice.EndToEndTestPOM.ordersPageValidation(EndToEndTestPOM.java:55)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:569)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ordersPageValidation -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:AutomationPractice.EndToEndTestPOM@7bd7d6d6]" started-at="2025-02-26T15:34:42 IST" name="closeBrowser" finished-at="2025-02-26T15:34:42 IST" duration-ms="138" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- AutomationPractice.EndToEndTestPOM -->
    </test> <!-- PurchaseOrder -->
  </suite> <!-- Suite -->
</testng-results>
